services:
  - type: web
    name: cloud-editor-03s5
    runtime: node
    repo: https://github.com/nikis-gif/cloud-editor
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
